-- insert into `match` ( `status`) values ('IN_PROGRESS');
-- insert into `match` ( `status`) values ('IN_PROGRESS');
-- insert into `match` ( `status`) values ('IN_PROGRESS');
-- insert into `match` ( `status`) values ('IN_PROGRESS');
-- insert into `match` ( `status`) values ('IN_PROGRESS');
-- insert into `match` ( `status`) values ('FINISHED');